language: node_js
node_js:
- 8
before_install:
- npm install -g node-gyp
before_script:
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
after_success:
  - chmod +x success.sh
  - ./success.sh
after_failure:
  - chmod +x fail.sh
  - ./fail.sh
cache:
  directories:
    - "node_modules"
branches:
  except:
  - hotfix