language: node_js
node_js:
- 8
services:
- mongodb
cache:
  directories:
  - node_modules
branches:
  except:
  - hotfix
before_install:
- openssl aes-256-cbc -K $encrypted_8ce681ad0d13_key -iv $encrypted_8ce681ad0d13_iv
  -in client-secret.json.enc -out client-secret.json -d
- openssl aes-256-cbc -K $encrypted_fbba68adb586_key -iv $encrypted_fbba68adb586_iv
  -in client-secret.json.enc -out client-secret.json -d
- ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine
- npm install -g node-gyp typescript
install:
- npm install
- tsc
before_script:
- export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
after_success:
- chmod +x ./scripts/build_success.sh
- "./scripts/build_success.sh"
after_failure:
- chmod +x ./scripts/build_fail.sh
- "./scripts/build_fail.sh"
before_deploy:
- zip -r dist dist/*
- mkdir -p dpl_cd_upload
- mv dist.zip dpl_cd_upload/dist.zip
deploy:
- provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: spudnik-bot
