version: 0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
environment:
  nodejs_version: '8'
  DISCORD_WEBHOOK_URL: https://discordapp.com/api/webhooks/463153585484595205/mUyCUGdPysUZW6XOOXseRWbFRQlnGeryl-rWx9iFei6MMTKY8hcD_yIKjSWuwfWAVO9V
install:
- npm install
cache: node_modules
build_script:
- ps: >-
    echo '--- Compiling... ---'
    tsc
    echo '--- Packaging Release Package... ---'
    zip -r release.zip dist/ config/ package.json README.md LICENSE
    echo '--- Packaging Deployment Package... ---'
    mv assets/prod/config.json config/config.json
    mv assets/servers.json config/servers.json
    zip -r deploy.zip config/ package.json src/ typings.d.ts tslint.json tsconfig.json typings.json LICENSE
test_script:
- sh: >-
    echo '--- Running Tests... ---'
    npm test
artifacts:
- path: /
  name: release
- path: /
  name: deploy
deploy:
- provider: AzureAppServiceZipDeploy
  website: Spudnik-bot
  username: spudnikgroup
  password:
    secure: 8sKz6Kmda3iej2eyQ/myJQ==
  artifact: deploy
  on:
    branch: master
- provider: GitHub
  auth_token:
    secure: aLGs8Z4ocl0pFD6NMmIZdULh50fDRyUXI39qbg6SRrqn+FDENlkMp+VKn/Gr9MLl
  artifact: release
  draft: true
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: true
- provider: AzureAppServiceZipDeploy
  website: Spudnik-bot-staging
  username: spudnikgroup
  password:
    secure: TJnEgflCrMIf6SxZdKCmcg==
  artifact: deploy
  on:
    branch: staging
notifications:
- provider: Webhook
  url: https://discordapp.com/api/webhooks/463153585484595205/mUyCUGdPysUZW6XOOXseRWbFRQlnGeryl-rWx9iFei6MMTKY8hcD_yIKjSWuwfWAVO9V
  method: POST
  body: >-
    {
      "embeds": [
        {
          "title": "Build #{{buildId}}",
          "url": "{{buildUrl}}",
          "color": {{#passed}}40973{{/passed}}{{^passed}}11672839{{/passed}},
          "footer": {
            "icon_url": "{{#passed}}https://i.imgur.com/Rf4g8v6.png{{/passed}}{{^passed}}https://i.imgur.com/QaERwAW.png{{/passed}}",
            "text": "{{#passed}}Success{{/passed}}{{^passed}}Failure{{/passed}}"
          },
          "author": {
            "name": "{{commitAuthor}}",
            "url": "https://github.com/{{repositoryName}}/commit/{{commitId}}"
          },
          "fields": [
            {
              "name": "Commit",
              "value": "{{branch}}/[#{{commitId}}](https://github.com/{{repositoryName}}/commit/{{commitId}}): {{commitMessage}}"
            },
            {
              "name": "Duration",
              "value": "{{duration}}",
              "inline": true
            },
            {
              "name": "Build version",
              "value": "{{buildVersion}}",
              "inline": true
            }
          ]
        }
      ]
    }
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false